import time

import requests
from fastapi import FastAPI

app = FastAPI(title='Weather API')

# Кэш в памяти: { "city_name": {"data": dict, "expires_at": float} }
WEATHER_CACHE = {}
CACHE_TTL_SECONDS = 30 * 60  # 30 минут

API_KEY = 'ВАШ_КЛЮЧ_OPENWEATHERMAP'  # Оставьте как есть, сработает заглушка


def get_weather_from_api(city: str) -> dict:
    """Получает данные от API или возвращает заглушку, если ключа нет."""
    url = f'http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric'
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            return {
                'temperature_c': data['main']['temp'],
                'pressure_mmhg': round(data['main']['pressure'] * 0.750062, 2),
                'wind_speed_ms': data['wind']['speed'],
            }
    except requests.RequestException:
        pass
    
    # Безопасная заглушка, если API недоступен или нет ключа
    return {
        'temperature_c': 22.5,
        'pressure_mmhg': 745.0,
        'wind_speed_ms': 3.2,
        'note': 'Generated by mock (Invalid API Key)',
    }


@app.get('/weather')
def get_weather(city: str):
    """Возвращает погоду в городе с учетом кэширования."""
    city_lower = city.lower()
    current_time = time.time()

    if city_lower in WEATHER_CACHE:
        cache_entry = WEATHER_CACHE[city_lower]
        if current_time < cache_entry['expires_at']:
            return cache_entry['data']

    weather_data = get_weather_from_api(city_lower)
    
    WEATHER_CACHE[city_lower] = {
        'data': weather_data,
        'expires_at': current_time + CACHE_TTL_SECONDS,
    }

    return weather_data